name: deploy-website

on:
  push:
    branches: ["main"]

  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4

      - name: Install Dependencies
        working-directory: ./website
        run: npm install

      - name: Build project
        working-directory: ./website
        run: npm run build -- --base=take-it-easy-ai/

      - name: Upload artifacts
        id: artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./website/dist/

  deploy:
    name: Deploy
    if: github.ref == 'refs/heads/main'
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write # to deploy to Pages
      id-token: write # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.artifacts.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
